sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t liamdonnellynyc/docker_hello_world -f Dockerfile.dev .

script:
    - docker run -e CI=true liamdonnellynyc/docker_hello_world npm run test

deploy:
  provider: "elasticbeanstalk"
  region: "eu-west-2"
  app: "docker_hello_world"
  env: "DockerHelloWorld-env"
  bucket_name: "elasticbeanstalk-eu-west-2-901797501160"
  bucket_path: "docker_hello_world"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure:
      "$AWS_SECRET_KEY"

